sap.ui.define([
	'model/dao/base/DTO',
	'model/dao/UserInline'
], function (DTO, UserInline) {
	"use strict";
	
	var UserInlineDTO = DTO.extend("com.team6.noblog.model.dao.UserInlineDTO", {
		
		// GETTER / SETTER
		// Mostly generated by the framework. Only the ones for local variables or
		// overridden getter / setter from the framework to alter the behavior ( readonly )
		
		// Getter
		
		getUserInline : function() {
			return this.getObject();
		},
		
		// Setter
		
		setUserInline : function(oUserInline) {
			this.setObject(oUserInline);
		},
		
		// ABSTRACT METHODS
		
		_onDataChanged: function(oEvent) {
			console.log("change");
		},
		
		_checkDataObject: function(oObject) {
			return (oObject instanceof UserInline);
		},
		
		_mapServiceDataToDTO: function(oData) {
			
			// Just for compatiblilty --------------------
			if( oData["userId"] ) {
				oData["userid"] = oData["userId"];
			}
			if( oData["userName"] ) {
				oData["username"] = oData["userName"];
			}
			// -------------------------------------------
			
			var sUserid 	= oData["userid"];
			var sUsername 	= oData["username"] || "Demo";
			
			return new UserInline(sUserid, sUsername);
		},
		
		_mapDTOToServiceData: function(oUserInline) {
			if(this._checkDataObject(oUserInline)) {
				return {
					userid 	: oUserInline.getUserid(),
					username: oUserInline.getUsername()
				}
			} else {
				throw new Error("No user inline data available!");
			}
		}
	});
	
	return UserInlineDTO;
});