sap.ui.define([
	'sap/ui/base/ManagedObject'
], function (ManagedObject) {
	"use strict";
	
	var Observable = ManagedObject.extend("com.team6.noblog.model.dao.base.Observable", {
		metadata : {
			events : {
				change : {
					
				}
			}
		},
		
		// GETTER / SETTER
		// Mostly generated by the framework. Only the ones for local variables or
		// overridden getter / setter from the framework to alter the behavior ( readonly )
		
		// General catch for property changes
		setProperty : function() {
			ManagedObject.prototype.setProperty.apply(this, arguments);
			this.fireChange();
		},
		
		// General catch for aggregation changes
		setAggregation: function() {
			ManagedObject.prototype.setAggregation.apply(this, arguments);
			this.fireChange();
		},
		
		addAggregation: function() {
			ManagedObject.prototype.addAggregation.apply(this, arguments);
			this.fireChange();
		},
		
		insertAggregation: function() {
			ManagedObject.prototype.insertAggregation.apply(this, arguments);
			this.fireChange();
		},
		
		removeAggregation: function() {
			ManagedObject.prototype.removeAggregation.apply(this, arguments);
			this.fireChange();
		},
		
		removeAllAggregation: function() {
			ManagedObject.prototype.removeAllAggregation.apply(this, arguments);
			this.fireChange();
		}
	});
	
	return Observable;
});